name: hh_news
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: "^3.0.0"

  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.1.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

